package jpmc_pb;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MortgageApplication implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID")
   private int id;
   @org.kie.api.definition.type.Label(value = "First Name")
   private java.lang.String firstName;

   public MortgageApplication()
   {
   }

   public int getId()
   {
      return this.id;
   }

   public void setId(int id)
   {
      this.id = id;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public MortgageApplication(int id, java.lang.String firstName)
   {
      this.id = id;
      this.firstName = firstName;
   }

}